openapi: 3.1.0
info:
  title: Workspace Imports Autosuggest API v2 View Catalogs data API
  description: 'API to programmatically trigger an existing workspace-scoped

    import in Bloomreach Engagement.

    '
  version: '2.1'
servers:
- url: https://api.bloomreach.com
  description: Bloomreach API
security:
- basicAuth: []
tags:
- name: View Catalogs data
paths:
  /accounts/{account_name}/catalogs:
    parameters:
    - $ref: '#/components/parameters/AccountName'
    get:
      tags:
      - View Catalogs data
      summary: Get all catalogs
      description: 'Get all the catalogs present for an account.

        '
      responses:
        200:
          description: OK. Click to see the response structure.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      catalogs:
                        type: array
                        items:
                          oneOf:
                          - $ref: '#/components/schemas/ProductCatalog'
                          - $ref: '#/components/schemas/ContentCatalog'
        401:
          description: Unauthorized
        404:
          description: Not found
        429:
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/429Response'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500Response'
  /accounts/{account_name}/catalogs/{catalog_name}/environments/{environment_name}:
    parameters:
    - $ref: '#/components/parameters/AccountName'
    - $ref: '#/components/parameters/CatalogName'
    - $ref: '#/components/parameters/EnvironmentName'
    get:
      tags:
      - View Catalogs data
      summary: Get catalog details
      description: 'View the current state of a catalog. This returns the entire catalog with product and item feed record data.

        '
      responses:
        200:
          description: OK. Click to see the response structure.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      catalog:
                        oneOf:
                        - $ref: '#/components/schemas/ProductCatalog'
                        - $ref: '#/components/schemas/ContentCatalog'
        401:
          description: Unauthorized
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  details:
                    type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found
        429:
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/429Response'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500Response'
components:
  schemas:
    429Response:
      description: Too Many Requests
      type: object
      properties:
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorResponse'
    ProductCatalog:
      type: object
      properties:
        name:
          type: string
        language:
          type: string
        data_type:
          type: string
        environment:
          type: string
        config_etag:
          type: string
        stats:
          $ref: '#/components/schemas/ProductCatalogStats'
        properties:
          $ref: '#/components/schemas/ProductCatalogProperties'
    ProductCatalogStats:
      type: object
      properties:
        last_index_update_config_etag:
          description: ''
          type: string
          example: 5613f704b80030ef908f1395100fbd1d
        last_index_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_index_refresh_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_feed_full_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_feed_delta_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_keyword_suggest_refresh_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        product_record_count:
          description: ''
          type: integer
        variant_record_count:
          description: ''
          type: integer
        product_doc_count:
          description: ''
          type: integer
        product_doc_byte_count:
          description: ''
          type: integer
        variant_doc_count:
          description: ''
          type: integer
        variant_doc_byte_count:
          description: ''
          type: integer
        catalog_searchable_byte_count:
          description: ''
          type: integer
        catalog_displayable_byte_count:
          description: ''
          type: integer
        catalog_facetable_manual_byte_count:
          description: ''
          type: integer
        catalog_facetable_auto_byte_count:
          description: ''
          type: integer
        product_view_override_record_count:
          description: ''
          type: integer
        variant_view_override_record_count:
          description: ''
          type: integer
        unique_view_count:
          description: ''
          type: integer
    ProductCatalogProperties:
      type: object
      properties:
        feed_version:
          description: ''
          type: integer
        index_version:
          description: ''
          type: integer
    ContentCatalogStats:
      type: object
      properties:
        last_index_update_config_etag:
          description: ''
          type: string
          example: 5613f704b80030ef908f1395100fbd1d
        last_index_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_feed_full_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        last_feed_delta_update_at:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        item_doc_count:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        item_record_count:
          description: ''
          format: date-time
          type: string
          example: '2024-01-01T00:00:00.000000Z'
        item_view_override_record_count:
          description: ''
          type: integer
    500Response:
      description: Internal Server Error
      type: object
      properties:
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        class:
          type: string
          enum:
          - error
          - warning
    ContentCatalog:
      type: object
      properties:
        name:
          type: string
        language:
          type: string
        data_type:
          type: string
        environment:
          type: string
        config_etag:
          type: string
        stats:
          $ref: '#/components/schemas/ContentCatalogStats'
  parameters:
    EnvironmentName:
      description: The type of environment you want to use for the request (Production/Staging).
      name: environment_name
      in: path
      schema:
        type: string
        minLength: 1
        maxLength: 64
        enum:
        - production
        - staging
      required: true
    CatalogName:
      description: '"Catalog name" is also called domain key. Use the same value as your domain key in your search API requests.'
      name: catalog_name
      in: path
      schema:
        type: string
        minLength: 1
        maxLength: 64
      required: true
      example: homeoasis_fr
    AccountName:
      description: Your unique account name.
      name: account_name
      in: path
      schema:
        type: string
        minLength: 1
        maxLength: 64
      required: true
      example: homeoasis
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: 'HTTP Basic authentication using an API Key ID and API Secret.

        For this workspace-scoped endpoint, use a workspace API key.


        `Authorization: Basic <base64(APIKeyID:APISecret)>`


        The API key must have the **Imports → Allow trigger imports**

        permission enabled in Workspace settings → Access management →

        API.

        '
